# Uncommented fields are required. Text <in brackets> is a placeholder and
# should be replaced with appropriate values.

api_key_id = "<app location api key id with owner role>"
api_key = "<app location api key with owner role>"
robot_id = "<robot id>"
part_id = "<part id>"

# serial_path = "<path to serial device, on Linux usually starts with /dev/ttyUSB>"
# serial_user = "<login username for the serial shell>"
# serial_pass = "<login password for the serial shell>"

[versions]
stable = '0.25.0'
old = '0.24.2'

# [wifi]
# ssid = "<wifi ssid>"
# password = "<wifi password>"
